### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by ivanling** [Xinyuan-LilyGO/LilyGo-HiGrow#34]
I try to compile in Arduino IDE 1.8.7, 
I get the folwing error:
`
`In` file included from ...\Documents\Arduino\libraries\LilyGo-HiGrow-master\src\src.ino:6:0:

...\Documents\Arduino\libraries\ESP-DASH-master\src/ESPDash.h:38:25: fatal error: ArduinoJson.h: No such file or directory

Multiple libraries were found for "WiFi.h"
compilation terminated.

 Used: ...\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi_old
exit status 1
Error compiling for board ESP32 Dev Module.`

Any Ideas?

**Comment by ivanling** [comment]
If I delete Arduino wifi lib and compile I get:

In file included from C:\Users\asus\Documents\Arduino\libraries\LilyGo-HiGrow-master\src\src.ino:6:0:

C:\Users\asus\Documents\Arduino\libraries\ESP-DASH-master\src/ESPDash.h:38:25: fatal error: ArduinoJson.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by lewisxhe** [comment]
Copy or move the folder in the lib directory to `<C:\Users\Your User Name\Documents\Arduino\libraries>` 

like :
![5](https://user-images.githubusercontent.com/22990954/114507776-2f5aa900-9c66-11eb-8e5b-4c58c187b0da.png)

**Comment by ivanling** [comment]
Hi, Thanks a lot.
After review my files and location, is that my problem. Now working fine but I have one more issue to solve. My board has DHT11 instead of DHT12. I go try to change that in code and I think I have to use other library to.
